server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      force: true
logging:
  file:
    name: classpath:/log/test.log  # 로깅 파일 위치이다.
    max-history: 7 # 로그 파일 삭제 주기이다. 7일 이후 로그는 삭제한다.
    max-size: 10MB  # 로그 파일 하나당 최대 파일 사이즈이다.
  level:  # 각 package 별로 로깅 레벨을 지정할 수 있다.
    "[com.project.study]" : error
    "[com.project.study.controller]" : debug
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: kkr0787@gmail.com
    password: wonbgdkwxwlwjhqo
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2: 
    console:
      enabled: true
  sql:
    init:
      schema-locations:
      - classpath:db/table.sql
      data-locations:
      - classpath:db/data.sql
  output:
    ansi:
      enabled: always
mybatis:
  mapper-locations:
  - classpath:mapper/**.xml    
  configuration:
    map-underscore-to-camel-case: true